import {CONFIG,PLANS,CATS,ART} from './config.js';
import {dateKey,plusDate,completed,activeCats,isRest,current,ensureRecord,reconcile,finishTask,claim,draw,revealLoss} from './model.js';
import {openStorage,readState,mutate,getMedia} from './storage.js';
let state,tab='home',recordMode='calendar',catFilter='all',calendarMonth=dateKey().slice(0,7),selectedCompare=[],busy=false,dialogKind='',lastDate=dateKey();
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog'),nav=document.querySelector('nav');
const urls=new Map();let renderVersion=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=(crop,cls='')=>{const [x,y,w,h]=Array.isArray(crop)?crop:ART[crop];return `<span aria-hidden="true" class="art ${cls}" style="aspect-ratio:${w}/${h};background-size:${1536/w*100}% ${1024/h*100}%;background-position:${x/(1536-w)*100}% ${y/(1024-h)*100}%"></span>`;};
const badge=rarity=>`<span class="rarity ${rarity}">${rarity}</span>`;
const bar=(value,max)=>`<div class="progress" role="progressbar" aria-label="完成进度" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="${max}"><div style="width:${Math.min(100,value/max*100)}%"></div></div>`;
const coin=()=>`<span class="coin">🪙 ${state.coins}</span>`;
const button=(action,label,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
async function commit(fn,media){const updated=await mutate(fn,media);state=updated.state;return updated.result;}
function showModal(title,body,kind='normal',closable=true){dialogKind=kind;dialog.innerHTML=`<div class="dialog-header"><h2 id="dialogTitle">${title}</h2>${closable?button('close','×','icon-btn','aria-label="关闭"'):''}</div><div class="dialog-body">${body}</div>`;if(!dialog.open)dialog.showModal();document.body.style.overflow='hidden';hydrate(dialog);}
function closeModal(){dialog.close();dialogKind='';document.body.style.overflow='';dialog.innerHTML='';}
dialog.addEventListener('cancel',e=>{if(['reward','loss','uploading'].includes(dialogKind)){e.preventDefault();return;}document.body.style.overflow='';dialogKind='';});
async function mediaUrl(key){if(!urls.has(key)){const blob=await getMedia(key);if(blob)urls.set(key,URL.createObjectURL(blob));}return urls.get(key);}
async function hydrate(root){for(const el of root.querySelectorAll('[data-media]')){const url=await mediaUrl(el.dataset.media);if(el.isConnected&&url)el.src=url;}}
function recordsWithPhotos(){const byDay=new Map();Object.values(state.records).sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>{if(r.media.front)byDay.set(r.day,r);});return [...byDay.values()].sort((a,b)=>a.day-b.day);}
function empty(message,crop='camera'){return `<div class="empty">${art(crop)}<p>${message}</p></div>`;}
function render(){
  if(!state)return;renderVersion++;
  const tabs=[['home','⌂','首页'],['today','▣','今日计划'],['cats','🐱','猫猫'],['me','♡','我的']];
  nav.innerHTML=tabs.map(([id,icon,name])=>`<button class="nav ${tab===id?'active':''}" data-action="nav" data-tab="${id}" ${tab===id?'aria-current="page"':''}><span class="ico" aria-hidden="true">${icon}</span><span>${name}</span></button>`).join('');
  main.innerHTML=`<section class="page" id="${tab}">${({home:renderHome,today:renderToday,cats:renderCats,me:renderMe})[tab]()}</section>`;hydrate(main);
}
function renderHome(){const r=current(state),n=completed(state).length,plan=PLANS[r.day-1];return `
  <div class="header"><div><div class="eyebrow">21 DAYS · FUTURE ME</div><h1>21天变更好计划</h1></div>${coin()}</div>
  <div class="card hero"><div class="hero-top"><span class="day">Day ${r.day} <small>/ 21</small></span><h2>一点一点，<br>变成喜欢的自己。</h2>${art('hero','hero-art')}</div>${bar(n,21)}<div class="progress-meta"><span>和猫猫一起，坚持了 ${n} 天</span><span>${Math.round(n/21*100)}%</span></div></div>
  <div class="today-summary"><div class="space"><b>今日训练</b><span class="muted">${r.tasks.length} / ${plan.tasks.length}</span></div>${bar(r.tasks.length,plan.tasks.length)}</div>
  <div class="checkin-cta">${button(n===21?'nav':r.completed?'nav':'checkin',n===21?'21 个训练日，完成啦 ♡':r.completed?'今日已完成 ✓':r.media.front?'📷 查看今日打卡':'📷 今日打卡','primary',(n===21||r.completed)?'data-tab="cats"':'')}${art(CATS[0].crop)}</div>
  ${isRest(state,dateKey())&&!r.completed?'<p class="placeholder-note">今天是计划休息日 · 放松一下也很好，不会扣猫猫</p>':''}
  <div class="section-title">我的成长记录</div><div class="segment" role="group" aria-label="记录模式">${[['calendar','日历'],['photos','照片'],['compare','对比']].map(([m,t])=>button('record-mode',t,m===recordMode?'active':'',`data-mode="${m}" aria-pressed="${m===recordMode}"`)).join('')}</div>
  <div class="card">${recordMode==='calendar'?renderCalendar():recordMode==='photos'?renderPhotos():renderCompare()}</div><p class="endnote">✧ 今天的小小努力，也在闪闪发光 ✧</p>`;}
function renderCalendar(){const [year,month]=calendarMonth.split('-').map(Number),first=new Date(year,month-1,1).getDay(),days=new Date(year,month,0).getDate();return `<div class="space month-control">${button('month','‹','','data-step="-1" aria-label="上个月"')}<b>${year}年 ${month}月</b>${button('month','›','','data-step="1" aria-label="下个月"')}</div><div class="calendar">${'日一二三四五六'.split('').map(d=>`<div class="cal-label">${d}</div>`).join('')}${'<span></span>'.repeat(first)}${Array.from({length:days},(_,i)=>{const key=`${calendarMonth}-${String(i+1).padStart(2,'0')}`,done=state.records[key]?.completed;return `<button class="cal-day ${done?'done':''} ${key===dateKey()?'today':''} ${isRest(state,key)&&!done?'rest':''}" data-action="calendar-day" data-date="${key}" aria-label="${key}${done?' 训练已完成':isRest(state,key)?' 休息日':''}">${i+1}</button>`;}).join('')}</div><div class="calendar-legend"><span><i></i>训练完成</span><span><i class="mint"></i>计划休息</span><span>细框 · 今天</span></div>`;}
function renderPhotos(){const rows=recordsWithPhotos();return `<div class="space"><b>训练日相册</b><span class="muted">${rows.length} 张正面照</span></div>${rows.length?`<div class="photo-grid">${rows.map(r=>`<button class="photo" data-action="photo" data-date="${r.date}" aria-label="查看第 ${r.day} 天照片"><img data-media="${esc(r.media.front)}" alt="第 ${r.day} 天正面照"><span>DAY ${r.day}</span></button>`).join('')}</div>`:empty('第一张照片，记录你的开始。')}`;}
function renderCompare(){const rows=recordsWithPhotos();if(rows.length<2)return empty('完成两个训练日的拍照，就能并排看变化啦。');if(!selectedCompare.length)selectedCompare=[rows[0].date,rows.at(-1).date];return `<b>和过去的自己，打个招呼</b><div class="compare" style="margin-top:14px">${[0,1].map(i=>{const r=rows.find(r=>r.date===selectedCompare[i])||rows[i];return `<div><select data-compare="${i}" aria-label="选择${i===0?'左':'右'}侧训练日">${rows.map(a=>`<option value="${a.date}" ${r.date===a.date?'selected':''}>Day ${a.day} · ${a.date.slice(5)}</option>`).join('')}</select><img data-media="${r.media.front}" alt="第 ${r.day} 天正面照"><small>${r.date}</small></div>`;}).join('')}</div>`;}
function renderToday(){const r=current(state),plan=PLANS[r.day-1];return `<div class="header"><div><div class="eyebrow">DAY ${r.day} / 21</div><h1>今天的训练</h1><div class="muted">${dateKey().replaceAll('-',' / ')}</div></div><span class="coin">${r.tasks.length} / ${plan.tasks.length}</span></div>
  <div class="today-banner">${art('hero')}<span class="bubble">今天也要加油呀！</span></div>
  ${completed(state).length===21&&!r.completed?`<div class="card">${empty('21 天的坚持，你做到了！','cheer')}${button('nav','看看我的成长','primary','data-tab="home"')}</div>`:!r.media.front?`<div class="card lock-card">${empty('先拍一张正面照<br>今天的训练就会为你打开。','lock')}${button('checkin','📷 去拍照，解锁计划')}</div>`:`<div class="today-summary"><div class="space"><b>${r.completed?'太棒了，今日计划完成！':'已完成 '+r.tasks.length+' / '+plan.tasks.length}</b><span class="muted">${Math.round(r.tasks.length/plan.tasks.length*100)}%</span></div>${bar(r.tasks.length,plan.tasks.length)}</div>${plan.tasks.map((t,i)=>`<button class="task ${r.tasks.includes(t.id)?'completed':''}" data-action="task" data-id="${t.id}" aria-label="${esc(t.name)} ${r.tasks.includes(t.id)?'已完成':'未完成'}"><span class="task-num">${i+1}</span>${art('avatar')}<span class="task-info"><b>${esc(t.name)}</b><small>${t.minutes} 分钟 · 查看详情</small></span><span class="check ${r.tasks.includes(t.id)?'done':''}" aria-hidden="true">${r.tasks.includes(t.id)?'✓':''}</span></button>`).join('')}${r.completed?button('question','今日人生问题已解锁 ♡','secondary',`data-day="${r.day}"`):''}`}
  ${plan.placeholder?'<p class="placeholder-note">任务与时长为占位内容 · 等待你的正式计划与视频</p>':''}`;}
function catCard(c,forDraw=false){const instances=state.cats.filter(x=>x.catId===c.id),home=instances.filter(x=>x.status==='home').length,known=instances.length>0;return `<${forDraw?'div':'button'} class="cat-card ${!known&&!forDraw?'unknown':known&&!home&&!forDraw?'away':''}" data-rarity="${c.rarity}" ${forDraw?'':`data-action="cat" data-id="${c.id}"`}>${art(known||forDraw?c.crop:'unknown')}<b>${known||forDraw?c.name:'？？？'}</b><br>${badge(c.rarity)}<small>${forDraw?'欢迎回家 ♡':home?'猫窝中 × '+home:known?'曾获得 · 出走中':'尚未解锁'}</small></${forDraw?'div':'button'}>`;}
function renderCats(){const discovered=new Set(state.cats.map(c=>c.catId)).size;return `<div class="header"><div><div class="eyebrow">A LITTLE CAT WORLD</div><h1>猫猫的小窝</h1></div>${coin()}</div><div class="card gacha-hero"><h2>下一只，会是心动的你吗？</h2><div class="cat-party">${art(CATS[12].crop)}${art(CATS[0].crop)}${art(CATS[20].crop)}</div><div class="gacha-actions">${button('draw','单抽<br><small>🪙 '+CONFIG.draw.price+'</small>','gacha-btn one','data-count="1"')}${button('draw','十连抽<br><small>🪙 '+CONFIG.draw.price*10+'</small>','gacha-btn ten','data-count="10"')}</div><div class="rates"><span>R 60%</span><span>S 30%</span><span>SSR 10%</span></div></div><div class="collection-heading"><b>猫猫图鉴</b><span>曾获得 ${discovered} / 24 · 猫窝 ${activeCats(state).length}</span></div><div class="filter">${[['all','全部'],['home','猫窝'],['away','出走中']].map(([f,t])=>button('cat-filter',t,f===catFilter?'active':'',`data-filter="${f}"`)).join('')}</div><div class="cat-grid">${CATS.filter(c=>catFilter==='all'||state.cats.some(x=>x.catId===c.id&&x.status===catFilter)).map(c=>catCard(c)).join('')}</div>${catFilter!=='all'&&!state.cats.some(x=>x.status===catFilter)?empty(catFilter==='home'?'猫窝在等第一位小住客。':'没有猫猫在外面流浪。','empty'):''}<p class="endnote">重复遇见，也是一次新的缘分 ♡</p>`;}
function renderMe(){const n=completed(state).length,r=current(state);return `<div class="header"><div class="eyebrow">A LETTER TO MYSELF</div>${button('settings','⚙','icon-btn','aria-label="设置"')}</div><div class="profile"><div class="avatar">${art('avatar')}</div><div><h2>${esc(state.name)} ♡</h2><div class="muted">正在变好的第 ${r.day} 个训练日</div><div style="margin-top:8px">${coin()}</div></div></div><div class="card stats"><div><b>${n}<small> / 21</small></b><small>完成训练日</small></div><div><b>${activeCats(state).length}</b><small>猫窝里的猫猫</small></div><div><b>${n}</b><small>已解锁问题</small></div></div><div class="card question"><div class="question-number">DAY ${r.day} · 今日问题</div><h3>${esc(PLANS[r.day-1].question)}</h3>${r.completed?button('question',state.answers[r.day]?.text?'看看我的回答':'去回答 ♡','primary',`data-day="${r.day}"`):'<p class="muted">🔒 完成今天的训练后解锁</p>'}<p class="muted">想写就写，跳过也没关系。</p></div><div class="section-title">写给自己的 21 个问题</div><div class="card question-list">${PLANS.map(p=>{const unlocked=completed(state).some(r=>r.day===p.day),a=state.answers[p.day];return `<button class="question-row" data-action="question" data-day="${p.day}" ${unlocked?'':'disabled'}><span>DAY<br>${String(p.day).padStart(2,'0')}</span><span><b>${unlocked?esc(p.question):'留给那一天的自己'}</b><small>${unlocked?(a?.text?'已回答 · 可以继续编辑':a?.skipped?'已跳过 · 随时回来补答':'已解锁 · 等你写下心里话'):'🔒 完成第 '+p.day+' 个训练日解锁'}</small></span></button>`;}).join('')}</div>`;}
function openCheckin(){if(completed(state).length>=21&&!current(state).completed)return;const r=current(state);showModal('今日打卡',`<p class="muted">正面照是今天的小小起点，其他都可选。</p><div class="media-grid">${[['front','正面照 · 必需'],['side','侧面照'],['back','背面照'],['video','1 分钟视频']].map(([type,name])=>`<div class="media-slot"><b>${name}</b><div class="media-preview">${r.media[type]?type==='video'?`<video data-media="${r.media[type]}" controls playsinline></video>`:`<img data-media="${r.media[type]}" alt="${name}">`:art(type==='video'?'today':'camera')}</div><div class="media-actions"><label>拍摄<input aria-label="拍摄${name}" type="file" accept="${type==='video'?'video/*':'image/*'}" capture="${type==='video'?'environment':'user'}" data-upload="${type}"></label><label>相册<input aria-label="上传${name}" type="file" accept="${type==='video'?'video/*':'image/*'}" data-upload="${type}"></label></div></div>`).join('')}</div><p class="upload-status" role="status">${r.media.front?'✓ 正面照已保存在这台设备':'照片和视频只保存在当前浏览器'}</p>${button('unlock','完成打卡，去训练 ✨','primary',r.media.front?'':'disabled')}`,'checkin');}
async function prepareMedia(file,type){
  if(type==='video'){
    if(!file.type.startsWith('video/'))throw Error('请选择视频文件。');
    if(file.size>100*1024*1024)throw Error('视频超过 100MB，请选一个较小的版本。');
    const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';
    try{await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('无法读取视频，请换一个 MP4 视频。')),15000);video.onloadedmetadata=()=>{clearTimeout(timeout);resolve();};video.onerror=()=>{clearTimeout(timeout);reject(Error('当前浏览器无法读取这个视频。'));};video.src=url;});if(!Number.isFinite(video.duration)||video.duration>CONFIG.maxVideoSeconds+1)throw Error('请选择 1 分钟以内的视频。');}finally{URL.revokeObjectURL(url);video.removeAttribute('src');video.load();}return file;
  }
  if(!file.type.startsWith('image/'))throw Error('请选择照片文件。');
  const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('照片处理失败。')),'image/jpeg',.86));}catch{throw Error('无法读取这张照片，请尝试 JPG、PNG 或手机相机照片。');}finally{URL.revokeObjectURL(url);}
}
async function upload(file,type){if(!file||busy)return;busy=true;dialogKind='uploading';const date=dateKey();document.querySelector('.upload-status').textContent='正在保存，请稍等…';dialog.querySelectorAll('input,button').forEach(b=>b.disabled=true);try{const blob=await prepareMedia(file,type),key=`${date}:${type}`;await commit(s=>{ensureRecord(s,date).media[type]=key;},{key,blob});if(urls.has(key)){URL.revokeObjectURL(urls.get(key));urls.delete(key);}render();openCheckin();}catch(e){openCheckin();toast(e.name==='QuotaExceededError'?'设备空间不足，照片未保存。请腾出空间后重试。':e.message);}finally{busy=false;dialogKind='checkin';}}
function openTask(id){const r=current(state);if(!r.media.front)return openCheckin();const t=PLANS[r.day-1].tasks.find(t=>t.id===id);if(!t)return;const safeUrl=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};const url=safeUrl(t.url),embed=safeUrl(t.embedUrl);let video=embed?`<iframe src="${esc(embed)}" title="${esc(t.name)}教学视频" allow="fullscreen; picture-in-picture" allowfullscreen></iframe>`:url&&/\.(mp4|webm|mov)(\?|$)/i.test(url)?`<video class="video-player" src="${esc(url)}" controls playsinline preload="metadata"></video>`:`<div class="video-placeholder"><span>▷</span>${url?'跟练视频已准备好':'跟练视频，等待加入'}</div>`;showModal(esc(t.name),`${video}${url?`<a class="video-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">打开跟练视频 ↗</a>`:''}<p class="space"><span>◷ ${t.minutes} 分钟</span><span class="muted">Day ${r.day}</span></p><p class="detail-copy">${esc(t.description)}</p><div class="detail-encouragement"><span>${esc(t.encouragement)}</span>${art('cheer')}</div>${button('complete-task',r.tasks.includes(id)?'已完成 ✓':'完成这个任务 ✓','primary',`data-id="${id}" ${r.tasks.includes(id)?'disabled':''}`)}`,'task');}
function pendingModal(){if(dialog.open)return;if(state.pendingLoss){showModal('有一只猫猫离家出走了……',`${art('away')}<p class="muted">有 ${state.pendingLoss.missed.length} 个应训练日没有完成。<br>我们从今天重新开始吧。</p>${button('reveal-loss','点击揭晓')}`,'loss',false);return;}const r=completed(state).find(r=>r.reward===null);if(r)showReward(r.date);}
function showReward(date){const r=state.records[date];showModal('今天的训练全部完成啦！',`${art('cheer')}<p class="muted">DAY ${r.day} COMPLETE · 问题已解锁</p><button class="packet-button" data-action="claim" data-date="${date}" aria-label="打开红包">${art('packet')}</button><p>小小红包，装着今天的惊喜</p>${button('claim','点击打开红包','primary',`data-date="${date}"`)}`,'reward',false);}
function openQuestion(day){if(!completed(state).some(r=>r.day===day))return;const a=state.answers[day];showModal(`Day ${day} · 人生问题`,`<h3>${esc(PLANS[day-1].question)}</h3><textarea id="answer" aria-label="问题回答" maxlength="10000" placeholder="写下你的想法吧…（可选）">${esc(a?.text||'')}</textarea>${button('save-answer','保存回答','primary',`data-day="${day}"`)}${button('skip-answer','这次先跳过','small-link',`data-day="${day}"`)}<p class="muted">跳过不影响训练和奖励，随时可以回来。</p>`,'question');}
function openSettings(){showModal('我的设置',`<div class="settings-row"><label for="username">用户名</label><input id="username" type="text" value="${esc(state.name)}" maxlength="20" style="width:65%"></div><div style="text-align:left"><b>每周计划休息日</b><div class="weekday-picker">${'日一二三四五六'.split('').map((d,i)=>`<label><input type="checkbox" name="restday" value="${i}" ${state.restWeekdays.includes(i)?'checked':''}><br>${d}</label>`).join('')}</div><p class="settings-note">休息日不推进训练日，也不会触发猫猫出走。调整从今天起生效。</p><b>临时休息日</b><div class="settings-row"><input id="restdate" type="date" min="${dateKey()}" aria-label="临时休息日期">${button('add-rest','添加','secondary')}</div><div class="rest-list">${state.restDates.filter(d=>d>=dateKey()).map(d=>button('remove-rest',d+' ×','',`data-date="${d}"`)).join('')}</div></div>${button('save-settings','保存设置')}<p class="settings-note">照片、视频和进度保存在当前设备的当前浏览器。换设备、换网址或清除网站数据不会带走这些记录。</p>`,'settings');}
async function action(el){const a=el.dataset.action;if(busy)return;
  if(a==='nav'){tab=el.dataset.tab;closeModal();render();window.scrollTo(0,0);return;}
  if(a==='close'){closeModal();pendingModal();return;}
  if(a==='checkin')return openCheckin();
  if(a==='unlock'){if(!current(state).media.front)return;closeModal();tab='today';render();return;}
  if(a==='record-mode'){recordMode=el.dataset.mode;render();return;}
  if(a==='month'){const d=new Date(calendarMonth+'-01T12:00:00');d.setMonth(d.getMonth()+Number(el.dataset.step));calendarMonth=dateKey(d).slice(0,7);render();return;}
  if(a==='calendar-day'){const r=state.records[el.dataset.date];if(r?.media.front)return showModal(`Day ${r.day} · ${r.date}`,`<img class="photo-view" data-media="${r.media.front}" alt="训练正面照"><p class="muted">${r.completed?'训练已完成 ✓':'当日训练未全部完成'}</p>`);toast(isRest(state,el.dataset.date)?'这一天是计划休息日。':'这一天还没有训练记录。');return;}
  if(a==='photo'){const r=state.records[el.dataset.date];showModal(`Day ${r.day} · ${r.date}`,`<img class="photo-view" data-media="${r.media.front}" alt="训练正面照">${['side','back'].filter(k=>r.media[k]).map(k=>`<p>${k==='side'?'侧面照':'背面照'}</p><img class="photo-view" data-media="${r.media[k]}" alt="${k==='side'?'侧面照':'背面照'}">`).join('')}${r.media.video?`<p>打卡视频</p><video class="video-player" data-media="${r.media.video}" controls playsinline></video>`:''}`);return;}
  if(a==='task')return openTask(el.dataset.id);
  if(a==='question')return openQuestion(Number(el.dataset.day));
  if(a==='settings')return openSettings();
  if(a==='cat-filter'){catFilter=el.dataset.filter;render();return;}
  if(a==='cat'){const c=CATS[Number(el.dataset.id)],instances=state.cats.filter(x=>x.catId===c.id);showModal(instances.length?c.name:'还没遇见的小猫',`${art(instances.length?c.crop:'unknown')}${badge(c.rarity)}<p>${instances.length?`猫窝中 ${instances.filter(x=>x.status==='home').length} 只 · 出走中 ${instances.filter(x=>x.status==='away').length} 只`:'下一次，会不会遇见它？'}</p>${instances.some(x=>x.status==='away')?'<p class="muted">曾获得的记录会一直保留。<br>找回功能会在以后加入。</p>':''}`);return;}
  busy=true;el.disabled=true;try{
    if(a==='complete-task'){await commit(s=>finishTask(s,el.dataset.id));closeModal();render();pendingModal();}
    if(a==='claim'){const amount=await commit(s=>claim(s,el.dataset.date));if(amount===null){closeModal();return;}render();showModal('红包打开啦！',`${art('opened')}<div class="coin-reward">+ ${amount} 金币</div><p class="muted">今天的小小坚持，已经被好好收藏。</p>${button('reward-next','收好奖励 ♡')}`,'reward-result',false);}
    if(a==='reward-next'){closeModal();pendingModal();}
    if(a==='draw'){const result=await commit(s=>draw(s,Number(el.dataset.count)));render();showModal(result.length===1?'一位新朋友来啦！':'十次相遇，都在这里',`<div class="draw-results ${result.length===1?'single':''}">${result.map(c=>catCard(c,true)).join('')}</div>${button('close','带回猫窝 ♡')}`);}
    if(a==='reveal-loss'){const c=await commit(revealLoss);render();showModal(c?`${c.name}，暂时出门了`:'猫猫记录已更新',`${art(c?c.crop:'away')}${c?badge(c.rarity):''}<p class="muted">图鉴里仍然保留着相遇的记录。<br>今天，也要好好照顾自己。</p>${button('loss-next','知道了，重新开始')}`,'loss-result',false);}
    if(a==='loss-next'){closeModal();pendingModal();}
    if(a==='save-answer'||a==='skip-answer'){const day=Number(el.dataset.day),text=document.querySelector('#answer').value;await commit(s=>{if(!completed(s).some(r=>r.day===day))throw Error('问题尚未解锁。');s.answers[day]={text:a==='save-answer'?text:(s.answers[day]?.text||''),skipped:a==='skip-answer',updatedAt:Date.now()};});closeModal();render();toast(a==='save-answer'?'回答已保存 ♡':'没关系，想写的时候再回来。');}
    if(['save-settings','add-rest','remove-rest'].includes(a)){const name=document.querySelector('#username').value.trim()||'邵邵',rest=[...dialog.querySelectorAll('[name=restday]:checked')].map(x=>Number(x.value)),date=document.querySelector('#restdate').value;await commit(s=>{s.name=name;s.restWeekdays=rest;if(a==='add-rest'){if(!date||date<dateKey())throw Error('请选择今天或未来的日期。');if(!s.restDates.includes(date))s.restDates.push(date);}if(a==='remove-rest')s.restDates=s.restDates.filter(d=>d!==el.dataset.date);});render();if(a==='save-settings'){closeModal();toast('设置已保存');}else openSettings();}
  }finally{busy=false;el.disabled=false;}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el).catch(e=>toast(e.message||'保存失败，请重试。'));});
document.addEventListener('change',e=>{if(e.target.dataset.upload)upload(e.target.files[0],e.target.dataset.upload);if(e.target.dataset.compare!==undefined){selectedCompare[Number(e.target.dataset.compare)]=e.target.value;render();}});
async function refresh(){if(busy||!state)return;try{if(lastDate!==dateKey()){lastDate=dateKey();if(dialog.open)closeModal();}await commit(s=>reconcile(s));render();pendingModal();}catch(e){toast('读取记录失败，请刷新重试。');}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh();});
setInterval(()=>{if(lastDate!==dateKey()&&document.visibilityState==='visible')refresh();},30000);
try{state=await openStorage();await commit(s=>reconcile(s));render();pendingModal();}catch(e){main.innerHTML=`<div class="page"><h1>猫窝还没准备好</h1><p>浏览器本地存储暂时不可用。请使用普通浏览模式，并允许网站保存数据。</p><button class="primary" onclick="location.reload()">重新试试</button></div>`;console.error(e);}

