import {initialState,migrateState} from './model.js';
export const DATA_BUILD='2026-09-29-auto-sync-v2';
let db;const result=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
export async function openStorage(){db=await new Promise((resolve,reject)=>{const req=indexedDB.open('future-me-v1',3);req.onupgradeneeded=()=>{for(const name of ['state','media','snapshots','meta'])if(!req.result.objectStoreNames.contains(name))req.result.createObjectStore(name);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const raw=await readState();await protectUpdate(raw);const state=migrateState(raw);if(raw?.version!==state.version)await replaceState(state);navigator.storage?.persist?.().catch(()=>{});return state;}
async function protectUpdate(raw){const meta=db.transaction('meta').objectStore('meta'),previous=await result(meta.get('dataBuild'));if(previous===DATA_BUILD)return;await new Promise((resolve,reject)=>{const tx=db.transaction(['snapshots','meta'],'readwrite'),snaps=tx.objectStore('snapshots');if(raw)snaps.put({build:previous||'legacy',savedAt:Date.now(),state:structuredClone(raw)},`${Date.now()}-${previous||'legacy'}`);tx.objectStore('meta').put(DATA_BUILD,'dataBuild');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});const store=db.transaction('snapshots','readwrite').objectStore('snapshots'),keys=await result(store.getAllKeys());for(const key of keys.slice(0,-5))await result(store.delete(key));}
export async function readState(){return (await result(db.transaction('state').objectStore('state').get('main')))||null;}
export function replaceState(state){return result(db.transaction('state','readwrite').objectStore('state').put(state,'main'));}
export function mutate(change,ops=[]){if(!Array.isArray(ops))ops=ops?[ops]:[];return new Promise((resolve,reject)=>{const tx=db.transaction(['state','media'],'readwrite');let state,out,failed,r=tx.objectStore('state').get('main');r.onsuccess=()=>{try{state=migrateState(r.result||initialState());out=change(state);state._updatedAt=Date.now();const store=tx.objectStore('media');for(const op of ops)op.delete?store.delete(op.key):store.put(op.blob,op.key);tx.objectStore('state').put(state,'main');}catch(e){failed=e;tx.abort();}};tx.oncomplete=()=>resolve({state,result:out});tx.onerror=()=>reject(failed||tx.error);tx.onabort=()=>reject(failed||tx.error||Error('保存失败，请重试。'));});}
export const getMedia=key=>result(db.transaction('media').objectStore('media').get(key));
export async function getAllMedia(){const store=db.transaction('media').objectStore('media'),keys=await result(store.getAllKeys()),items=[];for(const key of keys)items.push([key,await getMedia(key)]);return items;}
export async function auditMediaReferences(state){const existing=new Set(await result(db.transaction('media').objectStore('media').getAllKeys())),referenced=new Set();for(const record of Object.values(state.records||{}))for(const ref of Object.values(record.media||{})){if(typeof ref==='string')referenced.add(ref);else for(const key of Object.values(ref||{}))if(typeof key==='string')referenced.add(key)}for(const src of Object.values(state.videoSources||{}))if(src.uploadKey)referenced.add(src.uploadKey);return {referenced:referenced.size,stored:existing.size,missing:[...referenced].filter(key=>!existing.has(key)),orphans:[...existing].filter(key=>!referenced.has(key))}}
export async function restoreCloudSnapshot(state,media){await new Promise((resolve,reject)=>{const tx=db.transaction(['state','media'],'readwrite'),ss=tx.objectStore('state'),ms=tx.objectStore('media');ss.clear();ms.clear();ss.put(migrateState(state),'main');for(const [key,blob] of media)ms.put(blob,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});return migrateState(await readState());}
export async function clearAll(){await new Promise((resolve,reject)=>{const tx=db.transaction(['state','media'],'readwrite');tx.objectStore('state').clear();tx.objectStore('media').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
const blobData=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
export async function exportBackup(){const state=await readState(),store=db.transaction('media').objectStore('media'),keys=await result(store.getAllKeys()),media={},snapshots=await result(db.transaction('snapshots').objectStore('snapshots').getAll());for(const key of keys)media[key]=await blobData(await getMedia(key));return new Blob([JSON.stringify({format:'future-me-backup-v1',exportedAt:new Date().toISOString(),dataBuild:DATA_BUILD,state,snapshots,media})],{type:'application/json'});}
export async function importBackup(file){const p=JSON.parse(await file.text());if(p.format!=='future-me-backup-v1'||!p.state)throw Error('这不是有效的 Future Me 备份。');const decoded={};for(const [k,v] of Object.entries(p.media||{}))decoded[k]=await(await fetch(v)).blob();await new Promise((resolve,reject)=>{const tx=db.transaction(['state','media'],'readwrite'),ss=tx.objectStore('state'),ms=tx.objectStore('media');ss.clear();ms.clear();ss.put(migrateState(p.state),'main');for(const [k,b] of Object.entries(decoded))ms.put(b,k);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});return migrateState(await readState());}
