import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,ensureRecord,finishTask,claim,draw,reconcile,revealLoss,current,completed,activeCats} from '../model.js';
import {CATS,PLANS} from '../config.js';
const day='2026-09-29';
function finish(s,date=day){const r=ensureRecord(s,date);r.media.front=date+':front';PLANS[r.day-1].tasks.forEach(t=>finishTask(s,t.id,date));return r;}
test('photo gate, completion, question unlock and claim are separate; claim is idempotent',()=>{const s=initialState(day);assert.throws(()=>finishTask(s,'warmup',day));finish(s);assert.equal(completed(s).length,1);assert.equal(s.coins,0);assert.equal(claim(s,day,()=>0),10);assert.equal(claim(s,day,()=>.9),null);assert.equal(s.coins,10);finishTask(s,'warmup',day);assert.equal(s.records[day].tasks.length,3);});
test('all 21 training days advance by completion, never calendar gaps',()=>{const s=initialState(day);finish(s);assert.equal(current(s,'2026-10-05').day,2);const dates=Array.from({length:21},(_,i)=>`2026-10-${String(i+1).padStart(2,'0')}`);const cycle=initialState(dates[0]);dates.forEach(d=>finish(cycle,d));assert.equal(completed(cycle).length,21);assert.throws(()=>finishTask(cycle,'warmup','2026-11-01'));});
test('24 cats and repeated draws retain separate instances; insufficient balance does not mutate',()=>{assert.deepEqual(['R','S','SSR'].map(r=>CATS.filter(c=>c.rarity===r).length),[12,8,4]);const s=initialState(day);assert.throws(()=>draw(s,10));assert.equal(s.cats.length,0);s.coins=100;const result=draw(s,10,()=>0);assert.equal(result.length,10);assert.equal(activeCats(s).length,10);assert.equal(new Set(s.cats.map(c=>c.instanceId)).size,10);assert.equal(s.coins,0);});
test('planned rest is exempt; missed sessions reveal only one cat and preserve history',()=>{const s=initialState(day);s.coins=20;draw(s,1,()=>.99);s.restDates=['2026-09-29'];reconcile(s,'2026-09-30');assert.equal(s.pendingLoss,null);reconcile(s,'2026-10-03');assert.ok(s.pendingLoss);assert.equal(activeCats(s).length,1);assert.equal(revealLoss(s).rarity,'SSR');assert.equal(activeCats(s).length,0);assert.equal(s.cats.length,1);assert.equal(revealLoss(s),null);reconcile(s,'2026-10-03');assert.equal(s.pendingLoss,null);});
test('weekly rest and empty cat inventory never lose cats; finished cycle has no penalty',()=>{const s=initialState(day);s.restWeekdays=[2];s.coins=10;draw(s,1,()=>0);reconcile(s,'2026-09-30');assert.equal(s.pendingLoss,null);const blank=initialState(day);reconcile(blank,'2026-10-10');assert.equal(blank.pendingLoss,null);const done=initialState(day);for(let i=1;i<=21;i++)finish(done,`2026-10-${String(i).padStart(2,'0')}`);done.coins=10;draw(done,1,()=>0);reconcile(done,'2026-12-01');assert.equal(done.pendingLoss,null);});
