import test from 'node:test';
import assert from 'node:assert/strict';
import {CONFIG,PLANS,CATS,generateRewardPool} from '../config.js';
import {initialState,ensureRecord,finishTask,claim,draw,reconcile,revealDeparture,revealReturn,useLeave,useRecall,current,activeCats,awayCats} from '../model.js';
const start='2026-09-29';
function addFront(s,date=start){ensureRecord(s,date).media.front={full:`${date}:front`,thumb:`${date}:thumb`};}
function finish(s,date=start,random=()=>.5){addFront(s,date);let out;for(const t of PLANS[ensureRecord(s,date).day-1].tasks)out=finishTask(s,t.id,date,random);return out;}
function unlockCat(s,id=0,status='HOME'){const c=s.cats[id];c.unlocked=true;c.status=status;c.duplicateCount=1;c.obtainedAt=[Date.now()];return c;}

test('TEST 1/2: front photo gates training; full training opens exact saved reward',()=>{const s=initialState(start,()=>.4);assert.throws(()=>finishTask(s,PLANS[0].tasks[0].id,start),/正面照/);finish(s);assert.equal(s.coins,0);const expected=s.dailyRewardPool[0];assert.equal(claim(s,start),expected);assert.equal(s.coins,expected);assert.equal(claim(s,start),null);});
test('TEST 2/3: single costs 1 and ten costs 9 with ten complete results',()=>{const s=initialState(start);s.coins=10;assert.equal(draw(s,1,()=>0).length,1);assert.equal(s.coins,9);assert.equal(draw(s,10,()=>0).length,10);assert.equal(s.coins,0);});
test('TEST 4: pity 49 makes next draw SSR and resets; ten advances each draw',()=>{const s=initialState(start);s.coins=10;s.pityCounter=49;const one=draw(s,1,()=>0);assert.equal(one[0].rarity,'SSR');assert.equal(s.pityCounter,0);s.pityCounter=47;const ten=draw(s,10,()=>0);assert.equal(ten[2].rarity,'SSR');assert.equal(s.pityCounter,7);});
test('duplicates update unique catalog entry; drawing AWAY does not recall',()=>{const s=initialState(start);s.coins=3;const c=unlockCat(s,0,'AWAY');draw(s,1,()=>0);draw(s,1,()=>0);assert.equal(c.status,'AWAY');assert.equal(c.duplicateCount,3);assert.equal(s.cats.filter(x=>x.unlocked).length,1);});
test('TEST 5: missed day queues one departure, reveal preserves unlock/history',()=>{const s=initialState(start);const cat=unlockCat(s,20);reconcile(s,'2026-10-01',()=>0);assert.deepEqual(s.missedTrainingDays,[start,'2026-09-30']);assert.equal(s.pendingCatDepartureEvents.length,1);assert.equal(revealDeparture(s).id,cat.id);assert.equal(cat.status,'AWAY');assert.equal(cat.unlocked,true);assert.equal(cat.duplicateCount,1);reconcile(s,'2026-10-01');assert.equal(s.missedTrainingDays.length,2);});
test('multiple misses queue distinct HOME cats in order and no negative state',()=>{const s=initialState(start);unlockCat(s,0);unlockCat(s,1);reconcile(s,'2026-10-03',()=>0);assert.equal(s.pendingCatDepartureEvents.length,2);assert.notEqual(s.pendingCatDepartureEvents[0].catId,s.pendingCatDepartureEvents[1].catId);revealDeparture(s);revealDeparture(s);assert.equal(activeCats(s).length,0);assert.equal(revealDeparture(s),null);});
test('TEST 6: leave consumes one, does not advance day/streak/reward or create miss',()=>{const s=initialState(start);s.successfulTrainingStreak=2;assert.equal(useLeave(s,start),true);assert.equal(s.leaveTickets,1);assert.equal(s.trainingDay,1);assert.equal(s.successfulTrainingStreak,2);assert.equal(current(s,start).completed,false);reconcile(s,'2026-09-30');assert.equal(s.missedTrainingDays.length,0);});
test('TEST 7: five successful training days return random AWAY cat and reset streak',()=>{const s=initialState(start);const c=unlockCat(s,2,'AWAY');s.successfulTrainingStreak=4;finish(s,start,()=>0);assert.equal(s.pendingCatReturnEvents.length,1);assert.equal(s.successfulTrainingStreak,0);assert.equal(revealReturn(s).id,c.id);assert.equal(c.status,'HOME');});
test('TEST 8: fifth success without AWAY cat creates recall ticket',()=>{const s=initialState(start);s.successfulTrainingStreak=4;finish(s);assert.equal(s.catRecallTickets,1);assert.equal(s.successfulTrainingStreak,0);});
test('recall ticket returns selected cat',()=>{const s=initialState(start),c=unlockCat(s,3,'AWAY');s.catRecallTickets=1;useRecall(s,3);assert.equal(c.status,'HOME');assert.equal(s.catRecallTickets,0);});
test('TEST 9: rest day neither misses nor clears streak; leave is rejected',()=>{const s=initialState(start);s.successfulTrainingStreak=3;s.restDates=[start];reconcile(s,'2026-09-30');assert.equal(s.missedTrainingDays.length,0);assert.equal(s.successfulTrainingStreak,3);assert.throws(()=>useLeave(s,start),/休息日/);});
test('TEST 10: every generated 21-day reward pool is varied and exactly 300',()=>{for(let i=0;i<50;i++){let n=i;const p=generateRewardPool(()=>((n=n*1664525+1013904223)>>>0)/2**32);assert.equal(p.length,21);assert.equal(p.reduce((a,b)=>a+b,0),300);assert.ok(new Set(p).size>1);assert.ok(p.every(x=>x>=CONFIG.reward.min&&x<=CONFIG.reward.max));}});
test('catalog is fixed at R12/S8/SSR4 and config probabilities total 1',()=>{assert.deepEqual(['R','S','SSR'].map(r=>CATS.filter(c=>c.rarity===r).length),[12,8,4]);assert.equal(Object.values(CONFIG.draw.weights).reduce((a,b)=>a+b,0),1);});
